### ISSUE TITLE
Introduce Pipeline

### ISSUE THREAD

**Issue by cirocosta** [vmware-tanzu/cartographer#6]
```
As a supply chain author
I want to stamp immutable objects for changing inputs 
So that I can run immutable resources based on constrained resources (EG SCM commits)
```

* Pipeline CRD
* Template PipelineRun CRD
* When Pipeline changes - stamp new.

## Notes
Assume there are no completion rules and wait for condition ready True
Use a new PipelineController.

## Todo
- [x] Create Pipeline with params that can be used in RunTemplate
- [x] Create Runtemplate that lets us specify a template to stamp and selects for the Pipeline
- [x] Create Controller that stamps for pipelines
- [x] Ensure unit tests exist for static schema validation
- [x] Q: Do we need validating webhooks? not yet
- [x] Ensure each stamp creates a new object
- [x] change runTemplateName to runTemplateRef (to include namespacing)?
- [x] New story Q: Deal with templated naming versus `generateName`? reject templated naming, make new issue
- [x] ~react to template changes~ see issue #5
- [x] used 'Stub' instead of 'Returns' on fakes... clean that up
- [x] New story for Params
- [x] New story for adding pipeline to supply chain e2e
- [x] New story for changing the template causes a new reconcile/stamp - func mapping watcher thing
- [x] New story Patch less on status update
